<?php
// title
echo "<div id='dialogView' title='View Task'>";
echo "<form id='dialogFormView' class='form-horizontal' role='form'>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Task ID</label>";
echo "<div class='col-sm-9'>";
echo "<p class='lead' id='viewTaskId'></p>";
echo "</div>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Priority</label>";
echo "<div class='col-sm-9'>";
echo "<div class='' id='viewPriorities'></div>";
echo "</div>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Description</label>";
echo "<div class='col-sm-9'>";
echo "<div class='well well-sm' id='viewDescription'></div>";
echo "</div>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Status</label>";
echo "<div class='col-sm-9'>";
echo "<div class='well well-sm' id='viewStatus'></div>";
echo "</div>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Frequency</label>";
echo "<div class='col-sm-9'>";
echo "<div class='well well-sm' id='viewFrequency'></div>";
echo "</div>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Assigned To</label>"; 
echo "<div class='col-sm-9'>";
echo "<div class='well well-sm' id='viewAssigned'></div>";
echo "</div>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Due Date</label>"; 
echo "<div class='col-sm-9'>";    
echo "<div class='well well-sm' id='viewDateDue'></div>";
echo "</div>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Date Created</label>"; 
echo "<div class='col-sm-9'>";
echo "<div class='well well-sm' id='viewDateCreated'></div>";
echo "</div>";
echo "</div>";
echo "<div class='form-group'>";
echo "<label class='col-sm-3 control-label'>Date Completed</label>"; 
echo "<div class='col-sm-9'>";
echo "<div class='well well-sm' id='formDateCompleted'></div>";
echo "</div>";
echo "</div>";
echo "<div class='col-sm-offset-3 col-sm-1'>";
echo "<button type='submit' class='btn btn-default' name='close'>Close</button>";
echo "</div>";
echo "</form>";
echo "</div>";